package com.stock.util;

public class SQLQueryConstant {

    public static final String SQL_USER_LOGIN = "SELECT ID,USERNAME,ACTIVE_STATUS FROM USERS WHERE USERNAME=:USERNAME AND PASSWORD=:PASSWORD AND ACTIVE_STATUS='A' ";
    public static final String SQL_USER_STOCK = "SELECT USER_ID,STOCK_SYMBOL,STOCK_QTY FROM USER_STOCK_DATA WHERE USER_ID=:USERID";
    public static final String SQL_USER_STOCK_SYMBOL = "SELECT ID,USER_ID,STOCK_SYMBOL,STOCK_QTY FROM USER_STOCK_DATA WHERE USER_ID=:USERID AND STOCK_SYMBOL=:STOCK_SYMBOL";
    public static final String SQL_INSERT_STOCK = "INSERT INTO USER_STOCK_DATA (STOCK_QTY,USER_ID,STOCK_SYMBOL) values(?,?,?)";
    public static final String SQL_INSERT_STOCK_HIST = "INSERT INTO USER_STOCK_DATA_HIST (stock_data_id,stock_qty,stock_operation) values(?,?,?)";
    public static final String SQL_UPDATE_STOCK = "UPDATE USER_STOCK_DATA SET STOCK_QTY=? where USER_ID=? and STOCK_SYMBOL=?";
    public static final String SQL_HIST = "SELECT S.USER_ID,S.STOCK_SYMBOL,S.STOCK_QTY,H.CREATED_DATE,H.STOCK_OPERATION FROM USER_STOCK_DATA_HIST H, USER_STOCK_DATA S WHERE " +
            "S.ID=H.STOCK_DATA_ID AND S.USER_ID=:USERID";


}
